'''
NAME: BibleBookNames.py
PURPOSE: Maps the book abbreviations to their full names in the Bible (e.g. "Ge" -> "Genesis")
'''

class BibleBookNames:
    MAPPING = {
        # Old Testament
        "Ge": "Genesis",
        "Exo": "Exodus",
        "Lev": "Leviticus",
        "Num": "Numbers",
        "Deu": "Deuteronomy",
        "Josh": "Joshua",
        "Jdgs": "Judges",
        "Ruth": "Ruth",
        "1Sm": "1Samuel",
        "2Sm": "2Samuel",
        "1Ki": "1Kings",
        "2Ki": "2Kings",
        "1Chr": "1Chronicles",
        "2Chr": "2Chronicles",
        "Ezra": "Ezra",
        "Neh": "Nehemiah",
        "Est": "Esther",
        "Job": "Job",
        "Psa": "Psalms",
        "Prv": "Proverbs",
        "Eccl": "Ecclesiastes",
        "SSol": "Song of Solomon",
        "Isa": "Isaiah",
        "Jer": "Jeremiah",
        "Lam": "Lamentations",
        "Eze": "Ezekiel",
        "Dan": "Daniel",
        "Hos": "Hosea",
        "Joel": "Joel",
        "Amos": "Amos",
        "Obad": "Obadiah",
        "Jonah": "Jonah",
        "Mic": "Micah",
        "Nahum": "Nahum",
        "Hab": "Habakkuk",
        "Zep": "Zephaniah",
        "Hag": "Haggai",
        "Zec": "Zechariah",
        "Mal": "Malachi",
        # New Testament
        "Mat": "Matthew",
        "Mark": "Mark",
        "Luke": "Luke",
        "John": "John",
        "Acts": "Acts",
        "Rom": "Romans",
        "1Cor": "1Corinthians",
        "2Cor": "2Corinthians",
        "Gal": "Galatians",
        "Eph": "Ephesians",
        "Phi": "Philippians",
        "Col": "Colossians",
        "1Th": "1Thessalonians",
        "2Th": "2Thessalonians",
        "1Tim": "1Timothy",
        "2Tim": "2Timothy",
        "Titus": "Titus",
        "Phmn": "Philemon",
        "Heb": "Hebrews",
        "Jas": "James",
        "1Pet": "1Peter",
        "2Pet": "2Peter",
        "1Jn": "1John",
        "2Jn": "2John",
        "3Jn": "3John",
        "Jude": "Jude",
        "Rev": "Revelation"
    }